import java.text.SimpleDateFormat;
import javax.swing.JRadioButton;
import Clases.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sylar
 */
public class jDatosFuncionario extends javax.swing.JFrame {
    Integer intAccion;
    String strRut;
    
    public Integer getAccion( ){
        return this.intAccion;
    }
 
    public void setAccion(Integer Accion){
        this.intAccion = Accion;
    }
    
    public void setRut(String Rut){
        this.strRut = Rut;
    }

    /**
     * Creates new form jDatosFuncionario
     */
    
    public jDatosFuncionario() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpSistemaSalud = new javax.swing.ButtonGroup();
        grpSistemaPension = new javax.swing.ButtonGroup();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        tabDatosFuncionario = new javax.swing.JTabbedPane();
        tabDatosPersonales = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidoPaterno = new javax.swing.JTextField();
        txtApellidoMaterno = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        txtFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        tabDatosPrevisionales = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        optFonasa = new javax.swing.JRadioButton();
        optIsapre = new javax.swing.JRadioButton();
        cmbInstitucionSalud = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        optSistemaAntiguo = new javax.swing.JRadioButton();
        optSistemaNuevo = new javax.swing.JRadioButton();
        cmbSistemaAntiguo = new javax.swing.JComboBox<>();
        cmbSistemaNuevo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tabDatosPersonales.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Nombres");

        jLabel2.setText("Apellido Paterno");

        jLabel3.setText("Apellido Materno");

        jLabel4.setText("Fecha Nacimiento");

        jLabel5.setText("Direccion");

        jLabel6.setText("Telefono");

        jLabel7.setText("Celular");

        jLabel8.setText("Mail");

        txtFechaNacimiento.setDateFormatString("dd/MM/yyyy");

        jLabel9.setText("Rut");

        txtRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRutKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout tabDatosPersonalesLayout = new javax.swing.GroupLayout(tabDatosPersonales);
        tabDatosPersonales.setLayout(tabDatosPersonalesLayout);
        tabDatosPersonalesLayout.setHorizontalGroup(
            tabDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDatosPersonalesLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(tabDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabDatosPersonalesLayout.createSequentialGroup()
                        .addGroup(tabDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabDatosPersonalesLayout.createSequentialGroup()
                                .addGroup(tabDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabDatosPersonalesLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(14, 14, 14)))
                        .addGroup(tabDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtApellidoMaterno)
                            .addComponent(txtDireccion)
                            .addComponent(txtTelefono)
                            .addComponent(txtCelular)
                            .addComponent(txtMail, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addGroup(tabDatosPersonalesLayout.createSequentialGroup()
                                .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(tabDatosPersonalesLayout.createSequentialGroup()
                        .addGroup(tabDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(tabDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(txtApellidoPaterno)
                            .addComponent(txtRut)))))
        );
        tabDatosPersonalesLayout.setVerticalGroup(
            tabDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDatosPersonalesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(tabDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(tabDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(tabDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        txtRut.getAccessibleContext().setAccessibleDescription("");

        tabDatosFuncionario.addTab("Datos Personales", tabDatosPersonales);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Institucion Salud"));

        grpSistemaSalud.add(optFonasa);
        optFonasa.setText("FONASA");
        optFonasa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        optFonasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optFonasaActionPerformed(evt);
            }
        });

        grpSistemaSalud.add(optIsapre);
        optIsapre.setText("ISAPRE");
        optIsapre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optIsapreActionPerformed(evt);
            }
        });

        cmbInstitucionSalud.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optFonasa)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(optIsapre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbInstitucionSalud, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optFonasa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optIsapre)
                    .addComponent(cmbInstitucionSalud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Institucion Pension"));

        grpSistemaPension.add(optSistemaAntiguo);
        optSistemaAntiguo.setText("SISTEMA ANTIGUO");
        optSistemaAntiguo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optSistemaAntiguoActionPerformed(evt);
            }
        });

        grpSistemaPension.add(optSistemaNuevo);
        optSistemaNuevo.setText("AFP");
        optSistemaNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optSistemaNuevoActionPerformed(evt);
            }
        });

        cmbSistemaAntiguo.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optSistemaAntiguo)
                    .addComponent(optSistemaNuevo))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbSistemaAntiguo, 0, 211, Short.MAX_VALUE)
                    .addComponent(cmbSistemaNuevo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optSistemaNuevo)
                    .addComponent(cmbSistemaNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSistemaAntiguo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(optSistemaAntiguo))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tabDatosPrevisionalesLayout = new javax.swing.GroupLayout(tabDatosPrevisionales);
        tabDatosPrevisionales.setLayout(tabDatosPrevisionalesLayout);
        tabDatosPrevisionalesLayout.setHorizontalGroup(
            tabDatosPrevisionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDatosPrevisionalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabDatosPrevisionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabDatosPrevisionalesLayout.setVerticalGroup(
            tabDatosPrevisionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabDatosPrevisionalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabDatosFuncionario.addTab("Datos Previsionales", tabDatosPrevisionales);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar))
                    .addComponent(tabDatosFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(tabDatosFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnModificar)
                    .addComponent(btnCancelar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyyMMdd");
        clsFuncionario Fun = new clsFuncionario();
        
        Fun.setRut(txtRut.getText());
        Fun.setNombre(txtNombres.getText());
        Fun.setApellidoPaterno(txtApellidoPaterno.getText());
        Fun.setApellidoMaterno(txtApellidoMaterno.getText());
        //Fun.setFechaNacimiento(dateFormat.parse(txtFechaNacimiento.getDate()));
        Fun.setFechaNacimiento(String.format("%tY%tm%td",txtFechaNacimiento.getDate(),txtFechaNacimiento.getDate(),txtFechaNacimiento.getDate()));
        Fun.setDireccion(txtDireccion.getText());
        Fun.setTelefono(txtTelefono.getText());
        Fun.setCelular(txtCelular.getText());
        Fun.setMail(txtMail.getText());
        Fun.setSalud(cmbInstitucionSalud.getItemAt(cmbInstitucionSalud.getSelectedIndex()).getIdInstitucion());
        if (cmbSistemaNuevo.isEnabled()){
            Fun.setPension(cmbSistemaNuevo.getItemAt(cmbSistemaNuevo.getSelectedIndex()).getIdInstitucion());
        }else{
            Fun.setPension(cmbSistemaAntiguo.getItemAt(cmbSistemaAntiguo.getSelectedIndex()).getIdInstitucion());
        }
        if (Fun.GuardarFuncionario()){
            JOptionPane.showMessageDialog(this, "Funcionario agregado exitosamente!", "Datos guardados!", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error!", "Error en guardar datos!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void optIsapreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optIsapreActionPerformed
        // TODO add your handling code here:
        cmbInstitucionSalud.setEnabled(true);
    }//GEN-LAST:event_optIsapreActionPerformed

    private void optFonasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optFonasaActionPerformed
        // TODO add your handling code here:
        cmbInstitucionSalud.setEnabled(false);
    }//GEN-LAST:event_optFonasaActionPerformed

    private void optSistemaNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optSistemaNuevoActionPerformed
        // TODO add your handling code here:
        cmbSistemaAntiguo.setEnabled(false);
        cmbSistemaNuevo.setEnabled(true);
    }//GEN-LAST:event_optSistemaNuevoActionPerformed

    private void optSistemaAntiguoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optSistemaAntiguoActionPerformed
        // TODO add your handling code here:
        cmbSistemaAntiguo.setEnabled(true);
        cmbSistemaNuevo.setEnabled(false);
    }//GEN-LAST:event_optSistemaAntiguoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyyMMdd");
        clsFuncionario Fun = new clsFuncionario();
        
        Fun.setRut(txtRut.getText());
        Fun.setNombre(txtNombres.getText());
        Fun.setApellidoPaterno(txtApellidoPaterno.getText());
        Fun.setApellidoMaterno(txtApellidoMaterno.getText());
        //Fun.setFechaNacimiento(dateFormat.parse(txtFechaNacimiento.getDate()));
        Fun.setFechaNacimiento(String.format("%tY%tm%td",txtFechaNacimiento.getDate(),txtFechaNacimiento.getDate(),txtFechaNacimiento.getDate()));
        Fun.setDireccion(txtDireccion.getText());
        Fun.setTelefono(txtTelefono.getText());
        Fun.setCelular(txtCelular.getText());
        Fun.setMail(txtMail.getText());
        Fun.setSalud(cmbInstitucionSalud.getItemAt(cmbInstitucionSalud.getSelectedIndex()).getIdInstitucion());
        
        if (cmbSistemaNuevo.isEnabled()){
            Fun.setPension(cmbSistemaNuevo.getItemAt(cmbSistemaNuevo.getSelectedIndex()).getIdInstitucion());
        }else{
            Fun.setPension(cmbSistemaAntiguo.getItemAt(cmbSistemaAntiguo.getSelectedIndex()).getIdInstitucion());
        }
        if (Fun.ModificarFuncionario()){
            JOptionPane.showMessageDialog(this, "Funcionario modificado exitosamente!", "Datos guardados!", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error!", "Error en modificar datos!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtRutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutKeyTyped
        boolean max = txtRut.getText().length() > 8;
        if ( max ){
            evt.consume();
        }
    }//GEN-LAST:event_txtRutKeyTyped

    /**
     * @param args the command line arguments
     */
    
    public void Load(){ //Funcion para realizar la carga inicial del formulario
        clsSalud salud = new clsSalud();
        clsPension pension = new clsPension();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        salud.CargaInstitucionSalud(cmbInstitucionSalud);
        pension.LlenaComboInstitucionPension(cmbSistemaNuevo,"0");
        pension.LlenaComboInstitucionPension(cmbSistemaAntiguo,"1");
        
        optFonasa.setSelected(true);
        optSistemaNuevo.setSelected(true);
        
        try{
            
            if (intAccion==1){
                btnModificar.setVisible(false);
            }else{
                btnGuardar.setVisible(false);

                clsFuncionario Fun = new clsFuncionario();

                Fun.setRut(strRut);
                Fun.CargarFuncionario();

                txtRut.setText(Fun.getRut());
                txtNombres.setText(Fun.getNombre());
                txtApellidoPaterno.setText(Fun.getApellidoPaterno());
                txtApellidoMaterno.setText(Fun.getApellidoMaterno());
                txtFechaNacimiento.setDate(dateFormat.parse(Fun.getFechaNacimiento()));
                //txtFechaNacimiento.setDate(6, new java.sql.Date(Fun.getFechaNacimiento()));
                //Date FechaDate = dateFormat.parse(Fun.getFechaNacimiento());
                //txtFechaNacimiento.setDate(FechaDate);
                txtDireccion.setText(Fun.getDireccion());
                txtTelefono.setText(Fun.getTelefono());
                txtCelular.setText(Fun.getCelular());
                txtMail.setText(Fun.getMail());
                
                if (Fun.getSalud()!=00){
                    cmbInstitucionSalud.setSelectedIndex(Fun.getSalud()-1);
                    optIsapre.setSelected(true);
                    cmbInstitucionSalud.setEnabled(true);
                }
                
                clsPension Pension = new clsPension();
                Pension.CargaInstitucionPension(Fun.getPension());
                if (Pension.getTipo()!="0"){
                    cmbSistemaNuevo.setSelectedIndex(Fun.getPension()-1);
                }else{
                    cmbSistemaAntiguo.setSelectedIndex(Fun.getPension()-1);
                    optSistemaAntiguo.setSelected(true);
                    cmbSistemaAntiguo.setEnabled(true);
                }
            
            }
        } catch (Exception e) {
            e.printStackTrace();     
        }    
    } 
           
    public void  main(String args[]) {
        /* Set the Nimbus look and feel */

        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jDatosFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jDatosFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jDatosFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jDatosFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jDatosFuncionario().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<clsSalud> cmbInstitucionSalud;
    private javax.swing.JComboBox<clsPension> cmbSistemaAntiguo;
    private javax.swing.JComboBox<clsPension> cmbSistemaNuevo;
    private javax.swing.ButtonGroup grpSistemaPension;
    private javax.swing.ButtonGroup grpSistemaSalud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton optFonasa;
    private javax.swing.JRadioButton optIsapre;
    private javax.swing.JRadioButton optSistemaAntiguo;
    private javax.swing.JRadioButton optSistemaNuevo;
    private javax.swing.JTabbedPane tabDatosFuncionario;
    private javax.swing.JPanel tabDatosPersonales;
    private javax.swing.JPanel tabDatosPrevisionales;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtDireccion;
    private com.toedter.calendar.JDateChooser txtFechaNacimiento;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
